# -*- coding: utf-8 -*-
"""final-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnyl3Ron6FzEHswzSM7OyFoL1AifZXq0
"""

!pip install -q torch torchvision torchaudio transformers PyPDF2

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoTokenizer
import math
import re

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased",
    use_fast=True
)

print("Vocab size:", tokenizer.vocab_size)

# ---------- Embeddings ----------
class Embeddings(nn.Module):
    def __init__(self, vocab_size, d_model, max_pos=512):
        super().__init__()
        self.word = nn.Embedding(vocab_size, d_model)
        self.pos = nn.Embedding(max_pos, d_model)
        self.norm = nn.LayerNorm(d_model)

    def forward(self, input_ids):
        B, L = input_ids.shape
        pos_ids = torch.arange(L, device=input_ids.device).unsqueeze(0)
        return self.norm(self.word(input_ids) + self.pos(pos_ids))


# ---------- QKV ----------
class QKVProjector(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        self.q = nn.Linear(d_model, d_model)
        self.k = nn.Linear(d_model, d_model)
        self.v = nn.Linear(d_model, d_model)

    def forward(self, x):
        return self.q(x), self.k(x), self.v(x)


# ---------- Block Lanczos (stable stub for demo) ----------
class BlockLanczos(nn.Module):
    def __init__(self, num_blocks=8, block_size=4):
        super().__init__()
        self.k = num_blocks * block_size

    def forward(self, X):
        L, _ = X.shape
        basis = torch.randn(L, self.k, device=X.device)
        basis, _ = torch.linalg.qr(basis)
        T = torch.randn(self.k, self.k, device=X.device)
        return basis, T, {}


# ---------- Krylov Attention ----------
class KrylovAttention(nn.Module):
    def forward(self, Qb, Kb, Vb, TQ=None, TK=None, TV=None):
        """
        Qb, Kb, Vb : (L, k)
        """
        k = Qb.shape[1]

        Z0 = Qb.T @ Vb                    # (k, k)
        A = F.softmax(Z0 / math.sqrt(k), dim=-1)
        out = Qb @ A                     # (L, k)

        return out, None



# ---------- Krylov Output ----------
class KrylovOutputProjector(nn.Module):
    def __init__(self, k, d_model):
        super().__init__()
        self.proj = nn.Linear(k, d_model)

    def forward(self, x):
        return self.proj(x)


# ---------- Krylov-BERT Encoder ----------
class SpectralKrylovTransformerBlock(nn.Module):
    def __init__(self, vocab_size, d_model=128):
        super().__init__()
        self.emb = Embeddings(vocab_size, d_model)
        self.qkv = QKVProjector(d_model)
        self.lanczos = BlockLanczos()
        self.krylov = KrylovAttention()
        self.out_proj = KrylovOutputProjector(32, d_model)

    def forward(self, input_ids, attention_mask=None):
        x = self.emb(input_ids)
        Q, K, V = self.qkv(x)

        Qb, Kb, Vb = Q[0], K[0], V[0]
        BQ, TQ, _ = self.lanczos(Qb)

        Zk, _ = self.krylov(BQ, BQ, BQ, TQ, TQ, TQ)
        Z = self.out_proj(Zk)

        return Z.unsqueeze(0)

model = SpectralKrylovTransformerBlock(
    vocab_size=tokenizer.vocab_size,
    d_model=128
).to(device)

model.eval()
print("Krylov-BERT ready")

def show_matrix(name, x):
    print(f"\n{name}")
    print("Shape:", x.shape)
    print(x[:3, :5].detach().cpu())

sentence = "Spectral Krylov methods capture global structure."

enc = tokenizer(sentence, return_tensors="pt", padding="max_length", max_length=16)
input_ids = enc["input_ids"].to(device)

x = model.emb(input_ids)
Q, K, V = model.qkv(x)

BQ, _, _ = model.lanczos(Q[0])
Zk, _ = model.krylov(BQ, BQ, BQ)

show_matrix("Embeddings", x[0])
show_matrix("Query (Q)", Q[0])
show_matrix("Lanczos Basis (Q)", BQ)
show_matrix("Krylov Token Interaction (Zk)", Zk)

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]

if filename.endswith(".pdf"):
    import PyPDF2
    text = ""
    with open(filename, "rb") as f:
        reader = PyPDF2.PdfReader(f)
        for p in reader.pages:
            if p.extract_text():
                text += p.extract_text()
else:
    with open(filename, "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()

print(text[:500])

def clean_document(text):
    lines = text.splitlines()
    clean_lines = []

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # remove notebook / JSON noise
        if (
            line.startswith("{") or
            line.startswith("}") or
            line.startswith("\"") or
            "nbformat" in line or
            "cell_type" in line or
            "execution_count" in line
        ):
            continue

        clean_lines.append(line)

    return " ".join(clean_lines)


# ✅ IMPORTANT: clean *text*, not document_text
document_text = clean_document(text)

print(document_text[:500])

sentences = re.split(r'(?<=[.!?])\s+', text)
sentences = [s for s in sentences if len(s) > 30]

print("Total sentences:", len(sentences))
print(sentences[:3])

def encode_sentences(sentences):
    embs = []
    with torch.no_grad():
        for s in sentences:
            enc = tokenizer(
                s,
                return_tensors="pt",
                truncation=True,
                padding="max_length",
                max_length=32
            )
            out = model(enc["input_ids"].to(device))
            embs.append(out.mean(dim=1).squeeze(0).cpu())
    return torch.stack(embs)

sentence_embeddings = encode_sentences(sentences)
print("Embeddings shape:", sentence_embeddings.shape)

def extract_summary(sentences, embeddings, top_k=5):
    doc_emb = embeddings.mean(dim=0, keepdim=True)
    scores = F.cosine_similarity(embeddings, doc_emb)
    idx = torch.topk(scores, top_k).indices.tolist()
    idx = sorted(idx)
    return [sentences[i] for i in idx]

summary = extract_summary(sentences, sentence_embeddings)

print("===== KRYLOV-BERT SUMMARY =====")
for s in summary:
    print("-", s)



"""#ANOTHER"""

from transformers import BertModel
import time
import numpy as np

bert = BertModel.from_pretrained("bert-base-uncased").to(device)
bert.eval()

text = (
    "Spectral methods reduce attention complexity while preserving "
    "global structure in long sequence modeling tasks."
)

enc = tokenizer(
    text,
    return_tensors="pt",
    padding="max_length",
    truncation=True,
    max_length=128
)

input_ids = enc["input_ids"].to(device)
attention_mask = enc["attention_mask"].to(device)

def measure_time(fn, runs=20):
    times = []
    for _ in range(runs):
        start = time.time()
        with torch.no_grad():
            fn()
        times.append(time.time() - start)
    return np.mean(times), np.std(times)

bert_mean, bert_std = measure_time(
    lambda: bert(
        input_ids=input_ids,
        attention_mask=attention_mask
    )
)

print(f"BERT Encoder Time: {bert_mean:.4f} ± {bert_std:.4f} seconds")

krylov_mean, krylov_std = measure_time(
    lambda: model(
        input_ids=input_ids,
        attention_mask=attention_mask
    )
)

print(f"Krylov-BERT Encoder Time: {krylov_mean:.4f} ± {krylov_std:.4f} seconds")



"""#Long Doc Timings"""

import random, numpy as np, torch

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

long_text = document_text   # cleaned document text

def chunk_text(text, tokenizer, max_len=512):
    tokens = tokenizer(
        text,
        return_tensors="pt",
        truncation=False
    )["input_ids"][0]

    chunks = []
    for i in range(0, len(tokens), max_len):
        chunk = tokens[i:i+max_len]
        chunks.append(chunk)

    return chunks

chunks = chunk_text(long_text, tokenizer)
print(f"Total chunks: {len(chunks)}")

from transformers import BertModel
import time

bert = BertModel.from_pretrained("bert-base-uncased").to(device)
bert.eval()

def measure_time(fn, runs=3):
    times = []
    for _ in range(runs):
        start = time.time()
        with torch.no_grad():
            fn()
        times.append(time.time() - start)
    return sum(times) / len(times)

def run_bert():
    for chunk in chunks:
        input_ids = chunk.unsqueeze(0).to(device)
        attention_mask = torch.ones_like(input_ids)
        bert(input_ids=input_ids, attention_mask=attention_mask)

bert_time = measure_time(run_bert)

print(f"BERT total time on document: {bert_time:.3f} seconds")

def run_krylov():
    for chunk in chunks:
        input_ids = chunk.unsqueeze(0).to(device)
        attention_mask = torch.ones_like(input_ids)
        model(input_ids=input_ids, attention_mask=attention_mask)

krylov_time = measure_time(run_krylov)

print(f"Krylov-BERT total time on document: {krylov_time:.3f} seconds")

print(f"Speedup: {bert_time / krylov_time:.2f}×")



"""#With SUMMARY"""

import random, numpy as np, torch

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

import re

def split_into_sentences(text):
    text = text.replace("\n", " ")
    sentences = re.split(r'(?<=[.!?])\s+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 20]
    return sentences

sentences = split_into_sentences(document_text)
print("Total sentences:", len(sentences))

from transformers import BertModel

bert = BertModel.from_pretrained("bert-base-uncased").to(device)
bert.eval()

def bert_encode_sentences(sentences, tokenizer, bert, max_len=128):
    embeddings = []

    for s in sentences:
        enc = tokenizer(
            s,
            return_tensors="pt",
            truncation=True,
            padding="max_length",
            max_length=max_len
        )

        input_ids = enc["input_ids"].to(device)
        attention_mask = enc["attention_mask"].to(device)

        with torch.no_grad():
            out = bert(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

        # CLS token
        emb = out.last_hidden_state[:, 0, :]
        embeddings.append(emb.squeeze(0))

    return torch.stack(embeddings)

bert_sentence_embeddings = bert_encode_sentences(
    sentences, tokenizer, bert
)

print("BERT embeddings:", bert_sentence_embeddings.shape)

def krylov_encode_sentences(sentences, tokenizer, model, max_len=128):
    embeddings = []

    for s in sentences:
        enc = tokenizer(
            s,
            return_tensors="pt",
            truncation=True,
            padding="max_length",
            max_length=max_len
        )

        input_ids = enc["input_ids"].to(device)
        attention_mask = enc["attention_mask"].to(device)

        with torch.no_grad():
            out = model(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

        # CLS-like token (first token)
        emb = out[:, 0, :]
        embeddings.append(emb.squeeze(0))

    return torch.stack(embeddings)

krylov_sentence_embeddings = krylov_encode_sentences(
    sentences, tokenizer, model
)

print("Krylov embeddings:", krylov_sentence_embeddings.shape)

def extractive_summary(sentences, embeddings, top_k=5):
    scores = torch.norm(embeddings, dim=1)
    top_idx = torch.topk(scores, top_k).indices
    top_idx = sorted(top_idx.tolist())
    return [sentences[i] for i in top_idx]

bert_summary = extractive_summary(
    sentences,
    bert_sentence_embeddings,
    top_k=5
)

krylov_summary = extractive_summary(
    sentences,
    krylov_sentence_embeddings,
    top_k=5
)

print("\n===== BERT SUMMARY =====")
for s in bert_summary:
    print("-", s)

print("\n===== KRYLOV-BERT SUMMARY =====")
for s in krylov_summary:
    print("-", s)



"""#METRICS"""

!pip install -q bert-score

reference_summary = " ".join(bert_summary)
krylov_candidate = " ".join(krylov_summary)

print("REFERENCE (BERT):\n", reference_summary[:300])
print("\nCANDIDATE (KRYLOV):\n", krylov_candidate[:300])

from bert_score import score

P, R, F1 = score(
    cands=[krylov_candidate],
    refs=[reference_summary],
    lang="en",
    model_type="bert-base-uncased",
    verbose=False
)

print("===== BERTScore (Krylov vs BERT) =====")
print(f"Precision : {P.mean().item():.4f}")
print(f"Recall    : {R.mean().item():.4f}")
print(f"F1 Score  : {F1.mean().item():.4f}")

P0, R0, F10 = score(
    cands=[reference_summary],
    refs=[reference_summary],
    lang="en",
    model_type="bert-base-uncased"
)

print("\n===== BERT vs BERT (Upper Bound) =====")
print(f"F1 Score  : {F10.mean().item():.4f}")

def debug_spectral_krylov(model, input_ids, attention_mask=None):
    model.eval()
    with torch.no_grad():

        print("="*80)
        print("STAGE 1: EMBEDDINGS")
        print("="*80)

        x = model.embeddings(input_ids)
        print("Embeddings Shape:", x.shape)
        print(x[0, :3, :5])

        print("\n" + "="*80)
        print("STAGE 2: QKV PROJECTION")
        print("="*80)

        Q, K, V = model.qkv(x)
        print("Q shape:", Q.shape)
        print("K shape:", K.shape)
        print("V shape:", V.shape)
        print("Q sample:\n", Q[0, :3, :5])

        print("\n" + "="*80)
        print("STAGE 3: BLOCK LANCZOS")
        print("="*80)

        Qb = Q[0]
        Q_basis, T_Q, _ = model.lanczos(Qb)

        print("Basis shape:", Q_basis.shape)
        print("T_Q shape:", T_Q.shape)
        print("Basis sample:\n", Q_basis[:3, :5])

        print("\n" + "="*80)
        print("STAGE 4: KRYLOV ATTENTION")
        print("="*80)

        Zk, _ = model.krylov(Q_basis, Q_basis, Q_basis, T_Q, T_Q, T_Q)
        print("Z_k shape:", Zk.shape)
        print("Z_k sample:\n", Zk[:3, :5])

        print("\n" + "="*80)
        print("STAGE 5: PROJECTION BACK TO TOKEN SPACE")
        print("="*80)

        Z = model.k_proj(Zk)
        print("Projected shape:", Z.shape)
        print(Z[:3, :5])

        print("\n" + "="*80)
        print("STAGE 6: ILSC")
        print("="*80)

        ilsc_out = model.ilsc(Z, Zk)
        masks = ilsc_out["cluster_masks"]
        centroids = ilsc_out["centroids"]
        context = ilsc_out["cluster_context"]

        print("Cluster masks shape:", masks.shape)
        print(masks[:3, :5])
        print("Centroids shape:", centroids.shape)
        print(centroids[:3, :5])

        print("\n" + "="*80)
        print("STAGE 7: CONTEXTUALIZATION")
        print("="*80)

        ctx_out = model.context(ilsc_out)
        H = ctx_out["contextualized_embeddings"]
        print("Contextualized shape:", H.shape)
        print(H[:3, :5])

        print("\n" + "="*80)
        print("STAGE 8: FFN STACK")
        print("="*80)

        Hn = model.prenorm(H)
        ffn_out = model.ffn(Hn)
        final = model.postffn(H, ffn_out)

        print("Final output shape:", final.shape)
        print(final[:3, :5])

        print("\nDONE.")

text = document_text[:300]

enc = tokenizer(
    text,
    return_tensors="pt",
    padding="max_length",
    truncation=True,
    max_length=64
)

input_ids = enc["input_ids"].to(device)

with torch.no_grad():
    x = model.emb(input_ids)
    Q, K, V = model.qkv(x)

    BQ, TQ, _ = model.lanczos(Q[0])
    Zk, _ = model.krylov(BQ, BQ, BQ)

print("Embedding shape:", x.shape)
print("Basis shape:", BQ.shape)
print("Krylov output shape:", Zk.shape)

